Repository castore-dev/castore, pull requests merged in 2023-03, with the labels that each got.

#51 feature: create message queue class
  README.md
  packages/core/src/index.ts
  packages/core/src/messageBus/errors/index.ts
  packages/core/src/messaging/bus/errors/index.ts
  packages/core/src/messaging/bus/errors/messageBusEventStoreNotFound.ts
  packages/core/src/messaging/bus/errors/undefinedMessageBusAdapter.ts
  packages/core/src/messaging/bus/generics.ts
  packages/core/src/messaging/bus/index.ts
  packages/core/src/messaging/bus/messageBusAdapter.ts
  packages/core/src/messaging/bus/notificationMessageBus.ts
  packages/core/src/messaging/bus/stateCarryingMessageBus.ts
  packages/core/src/messaging/index.ts
  packages/core/src/messaging/notificationMessage.ts
  packages/core/src/messaging/queue/errors/index.ts
  packages/core/src/messaging/queue/errors/messageQueueEventStoreNotFound.ts
  packages/core/src/messaging/queue/errors/undefinedMessageQueueAdapter.ts
  packages/core/src/messaging/queue/generics.ts
  packages/core/src/messaging/queue/index.ts
  packages/core/src/messaging/queue/messageQueueAdapter.ts
  packages/core/src/messaging/queue/notificationMessageQueue.ts
  packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
  packages/core/src/messaging/stateCarryingMessage.ts
  packages/event-bridge-message-bus-adapter/src/message.ts
Labels: minor

#52 feature: Create sqs message queue adapter
  .github/workflows/release-to-npm.yml
  castore.code-workspace
  packages/core/src/index.ts
  packages/event-bridge-message-bus-adapter/src/eventBridge.ts
  packages/event-bridge-message-bus-adapter/src/message.ts
  packages/sqs-message-queue-adapter/.eslintignore
  packages/sqs-message-queue-adapter/.lintstagedrc.js
  packages/sqs-message-queue-adapter/README.md
  packages/sqs-message-queue-adapter/babel.config.js
  packages/sqs-message-queue-adapter/dependency-cruiser.js
  packages/sqs-message-queue-adapter/package.json
  packages/sqs-message-queue-adapter/project.json
  packages/sqs-message-queue-adapter/src/index.ts
  packages/sqs-message-queue-adapter/src/message.ts
  packages/sqs-message-queue-adapter/src/sqs.ts
  packages/sqs-message-queue-adapter/tsconfig.build.json
  packages/sqs-message-queue-adapter/tsconfig.json
  packages/sqs-message-queue-adapter/vite.config.js
  workspace.json
  yarn.lock
Labels: minor

#53 feature: create in-memory queue adapter
  .github/workflows/release-to-npm.yml
  castore.code-workspace
  packages/core/src/index.ts
  packages/core/src/messaging/anyMessage.ts
  packages/core/src/messaging/index.ts
  packages/dynamodb-event-storage-adapter/src/utils/formatEventForTransaction.unit.test.ts
  packages/dynamodb-event-storage-adapter/src/utils/pushEventsTransaction.unit.test.ts
  packages/in-memory-message-queue-adapter/.eslintignore
  packages/in-memory-message-queue-adapter/.lintstagedrc.js
  packages/in-memory-message-queue-adapter/README.md
  packages/in-memory-message-queue-adapter/babel.config.js
  packages/in-memory-message-queue-adapter/dependency-cruiser.js
  packages/in-memory-message-queue-adapter/package.json
  packages/in-memory-message-queue-adapter/project.json
  packages/in-memory-message-queue-adapter/src/index.ts
  packages/in-memory-message-queue-adapter/src/queue.ts
  packages/in-memory-message-queue-adapter/src/queue.unit.test.ts
  packages/in-memory-message-queue-adapter/tsconfig.build.json
  packages/in-memory-message-queue-adapter/tsconfig.json
  packages/in-memory-message-queue-adapter/vite.config.js
  workspace.json
  yarn.lock
Labels: minor

#54 feature: create in-memory bus adapter
  .github/workflows/release-to-npm.yml
  castore.code-workspace
  packages/in-memory-message-bus-adapter/.eslintignore
  packages/in-memory-message-bus-adapter/.lintstagedrc.js
  packages/in-memory-message-bus-adapter/README.md
  packages/in-memory-message-bus-adapter/babel.config.js
  packages/in-memory-message-bus-adapter/dependency-cruiser.js
  packages/in-memory-message-bus-adapter/package.json
  packages/in-memory-message-bus-adapter/project.json
  packages/in-memory-message-bus-adapter/src/inMemory.ts
  packages/in-memory-message-bus-adapter/src/inMemory.unit.test.ts
  packages/in-memory-message-bus-adapter/src/index.ts
  packages/in-memory-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/tsconfig.build.json
  packages/in-memory-message-bus-adapter/tsconfig.json
  packages/in-memory-message-bus-adapter/vite.config.js
  workspace.json
  yarn.lock
Labels: minor

#56 fix: Add retry policy to in memory message bus and queue
  packages/in-memory-message-bus-adapter/src/inMemory.ts
  packages/in-memory-message-bus-adapter/src/inMemory.unit.test.ts
  packages/in-memory-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/src/types.ts
  packages/in-memory-message-bus-adapter/src/utils.ts
  packages/in-memory-message-queue-adapter/src/queue.ts
  packages/in-memory-message-queue-adapter/src/queue.unit.test.ts
  packages/in-memory-message-queue-adapter/src/utils.ts
Labels: patch

#57 feature: Document message buses and queues
  README.md
  packages/core/src/eventStore/generics.ts
  packages/core/src/index.ts
  packages/core/src/messaging/anyMessage.ts
  packages/core/src/messaging/bus/messageBusAdapter.ts
  packages/core/src/messaging/bus/notificationMessageBus.ts
  packages/core/src/messaging/bus/stateCarryingMessageBus.ts
  packages/core/src/messaging/index.ts
  packages/core/src/messaging/message.ts
  packages/core/src/messaging/notificationMessage.ts
  packages/core/src/messaging/queue/generics.ts
  packages/core/src/messaging/queue/index.ts
  packages/core/src/messaging/queue/messageQueueAdapter.ts
  packages/core/src/messaging/queue/notificationMessageQueue.ts
  packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
  packages/core/src/messaging/stateCarryingMessage.ts
  packages/dynamodb-event-storage-adapter/README.md
  packages/event-bridge-message-bus-adapter/README.md
  packages/event-bridge-message-bus-adapter/src/eventBridge.ts
  packages/event-bridge-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/README.md
  packages/in-memory-message-bus-adapter/src/inMemory.ts
  packages/in-memory-message-bus-adapter/src/inMemory.unit.test.ts
  packages/in-memory-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/src/types.ts
  packages/in-memory-message-bus-adapter/src/utils.ts
  packages/in-memory-message-queue-adapter/README.md
  packages/in-memory-message-queue-adapter/src/queue.ts
  packages/in-memory-message-queue-adapter/src/queue.unit.test.ts
  packages/inmemory-event-storage-adapter/README.md
  packages/json-schema-command/README.md
  packages/json-schema-event/README.md
  packages/redux-event-storage-adapter/README.md
  packages/sqs-message-queue-adapter/README.md
  packages/sqs-message-queue-adapter/src/message.ts
  packages/test-tools/README.md
  packages/zod-event/README.md
Labels: minor

#58 fix: Document new messaging packages
  README.md
  packages/event-bridge-message-bus-adapter/README.md
  packages/event-bridge-message-bus-adapter/package.json
  packages/event-bridge-message-bus-adapter/src/eventBridge.unit.test.ts
  packages/sqs-message-queue-adapter/README.md
  packages/sqs-message-queue-adapter/package.json
  packages/sqs-message-queue-adapter/src/message.ts
  packages/sqs-message-queue-adapter/src/sqs.unit.test.ts
  yarn.lock
Labels: patch

#60 fix: Document last messaging packages
  README.md
  packages/core/src/index.ts
  packages/core/src/messaging/bus/generics.ts
  packages/core/src/messaging/bus/index.ts
  packages/core/src/messaging/queue/generics.ts
  packages/core/src/messaging/queue/index.ts
  packages/in-memory-message-bus-adapter/README.md
  packages/in-memory-message-bus-adapter/src/inMemory.unit.test.ts
  packages/in-memory-message-queue-adapter/README.md
  packages/in-memory-message-queue-adapter/src/queue.ts
  packages/in-memory-message-queue-adapter/src/queue.unit.test.ts
  packages/inmemory-event-storage-adapter/README.md
  packages/test-tools/README.md
Labels: patch

#61 fix: use upper case for generics
  demo/implementation/libs/middlewares/console.ts
  packages/core/src/command/command.ts
  packages/core/src/event/eventDetail.ts
  packages/core/src/event/eventType.ts
  packages/core/src/eventStore/eventStore.ts
  packages/core/src/eventStore/generics.ts
  packages/core/src/eventStore/types.ts
  packages/core/src/messaging/bus/generics.ts
  packages/core/src/messaging/bus/notificationMessageBus.ts
  packages/core/src/messaging/bus/stateCarryingMessageBus.ts
  packages/core/src/messaging/message.ts
  packages/core/src/messaging/queue/generics.ts
  packages/core/src/messaging/queue/notificationMessageQueue.ts
  packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
  packages/core/src/utils.ts
  packages/dynamodb-event-storage-adapter/src/utils/formatEventForTransaction.ts
  packages/event-bridge-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/src/inMemory.ts
  packages/in-memory-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/src/types.ts
  packages/in-memory-message-queue-adapter/src/queue.ts
  packages/json-schema-command/src/jsonSchema.ts
  packages/json-schema-event/src/jsonSchema.ts
  packages/react-visualizer/src/Visualizer.tsx
  packages/redux-event-storage-adapter/src/configureCastore.ts
  packages/redux-event-storage-adapter/src/hooks/useAggregate.ts
  packages/redux-event-storage-adapter/src/hooks/useAggregateEvents.ts
  packages/redux-event-storage-adapter/src/hooks/useAggregateIds.ts
  packages/redux-event-storage-adapter/src/hooks/useExistingAggregate.ts
  packages/redux-event-storage-adapter/src/types.ts
  packages/sqs-message-queue-adapter/src/message.ts
  packages/test-tools/src/mockEventStore.ts
  packages/test-tools/src/mockedEventStore.ts
  packages/test-tools/src/muteEventStore.ts
  packages/zod-event/src/zodEvent.ts
Labels: patch

#62 fix: Test dynamodb adapter
  packages/core/src/storageAdapter.ts
  packages/dynamodb-event-storage-adapter/package.json
  packages/dynamodb-event-storage-adapter/src/adapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
  packages/dynamodb-event-storage-adapter/src/index.ts
  packages/dynamodb-event-storage-adapter/src/utils/formatEventForTransaction.ts
  packages/dynamodb-event-storage-adapter/src/utils/formatEventForTransaction.unit.test.ts
  packages/dynamodb-event-storage-adapter/src/utils/pushEventsTransaction.unit.test.ts
  packages/event-bridge-message-bus-adapter/src/adapter.ts
  packages/event-bridge-message-bus-adapter/src/adapter.unit.test.ts
  packages/event-bridge-message-bus-adapter/src/index.ts
  packages/in-memory-message-bus-adapter/src/adapter.ts
  packages/in-memory-message-bus-adapter/src/adapter.unit.test.ts
  packages/in-memory-message-bus-adapter/src/index.ts
  packages/in-memory-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/src/types.ts
  packages/in-memory-message-bus-adapter/src/utils.ts
  packages/in-memory-message-queue-adapter/src/adapter.ts
  packages/in-memory-message-queue-adapter/src/adapter.unit.test.ts
  packages/in-memory-message-queue-adapter/src/index.ts
  packages/inmemory-event-storage-adapter/src/adapter.ts
  packages/inmemory-event-storage-adapter/src/adapter.unit.test.ts
  packages/inmemory-event-storage-adapter/src/index.ts
  packages/json-schema-command/src/command.ts
  packages/json-schema-command/src/command.type.test.ts
  packages/json-schema-command/src/command.unit.test.ts
  packages/json-schema-command/src/command.util.test.ts
  packages/json-schema-command/src/index.ts
  packages/json-schema-event/src/eventType.ts
  packages/json-schema-event/src/eventType.unit.test.ts
  packages/json-schema-event/src/index.ts
  packages/redux-event-storage-adapter/src/adapter.ts
  packages/redux-event-storage-adapter/src/configureCastore.ts
  packages/redux-event-storage-adapter/src/hooks/useAggregateEvents.ts
  packages/redux-event-storage-adapter/src/hooks/useAggregateIds.ts
  packages/redux-event-storage-adapter/src/index.ts
  packages/sqs-message-queue-adapter/src/adapter.ts
  packages/sqs-message-queue-adapter/src/adapter.unit.test.ts
  packages/sqs-message-queue-adapter/src/index.ts
  packages/zod-event/src/eventType.ts
  packages/zod-event/src/eventType.unit.test.ts
  packages/zod-event/src/index.ts
  yarn.lock
Labels: patch

#63 feature: Support initial event date filtering and reverse options in list aggregate ids
  packages/core/src/eventStore/eventStore.ts
  packages/core/src/eventStore/eventStore.unit.test.ts
  packages/core/src/storageAdapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
  packages/dynamodb-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
  packages/inmemory-event-storage-adapter/src/adapter.ts
  packages/inmemory-event-storage-adapter/src/adapter.unit.test.ts
  packages/inmemory-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
  packages/redux-event-storage-adapter/src/adapter.ts
  packages/redux-event-storage-adapter/src/hooks/useAggregateIds.ts
  packages/redux-event-storage-adapter/src/utils/parseAppliedListAggregateIdsOptions.ts
Labels: minor

#64 fix: update documentation
  README.md
  docs/building-your-own-event-storage-adapter.md
  docs/the-five-rules-of-event-sourcing.md
Labels: patch

#65 fix: rework types following real life usage pbs
  packages/core/src/messaging/message.ts
  packages/in-memory-message-bus-adapter/src/message.ts
Labels: patch

#67 feature: Create connected event store class
  README.md
  packages/core/src/command/command.type.test.ts
  packages/core/src/command/command.unit.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.ts
  packages/core/src/connectedEventStore/connectedEventStore.type.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.util.test.ts
  packages/core/src/connectedEventStore/index.ts
  packages/core/src/eventStore/eventStore.ts
  packages/core/src/eventStore/eventStore.type.test.ts
  packages/core/src/eventStore/eventStore.unit.test.ts
  packages/core/src/eventStore/eventStore.util.test.ts
  packages/core/src/eventStore/types.ts
  packages/core/src/index.ts
  packages/core/src/messaging/bus/notificationMessageBus.ts
  packages/core/src/messaging/bus/stateCarryingMessageBus.ts
  packages/core/src/messaging/queue/notificationMessageQueue.ts
  packages/core/src/messaging/queue/notificationMessageQueue.type.test.ts
  packages/core/src/messaging/queue/notificationMessageQueue.util.test.ts
  packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
  packages/json-schema-command/src/command.type.test.ts
Labels: minor

#78 fix: remove dynamodb dependency from dynamodb event storage adapter
  packages/dynamodb-event-storage-adapter/package.json
Labels: patch

#77 chore: Rework documentation examples
  README.md
  docs/building-your-own-event-storage-adapter.md
  packages/core/src/command/command.fixtures.test.ts
  packages/core/src/command/command.type.test.ts
  packages/core/src/command/command.unit.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.fixtures.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.ts
  packages/core/src/connectedEventStore/connectedEventStore.type.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.util.test.ts
  packages/core/src/eventStore/eventStore.fixtures.test.ts
  packages/core/src/eventStore/eventStore.type.test.ts
  packages/core/src/eventStore/eventStore.unit.test.ts
  packages/core/src/eventStore/eventStore.util.test.ts
  packages/core/src/messaging/queue/notificationMessageQueue.fixtures.test.ts
  packages/core/src/messaging/queue/notificationMessageQueue.type.test.ts
  packages/dynamodb-event-storage-adapter/README.md
  packages/event-bridge-message-bus-adapter/README.md
  packages/in-memory-message-bus-adapter/README.md
  packages/inmemory-event-storage-adapter/README.md
  packages/json-schema-command/README.md
  packages/json-schema-command/src/command.fixtures.test.ts
  packages/json-schema-command/src/command.type.test.ts
  packages/json-schema-command/src/command.unit.test.ts
  packages/json-schema-event/README.md
  packages/redux-event-storage-adapter/README.md
  packages/sqs-message-queue-adapter/README.md
  packages/test-tools/README.md
  packages/zod-event/README.md
Labels: ignore-for-release

#76 feature: add publishMessages to MessageQueueAdapter
  packages/core/src/messaging/queue/messageQueueAdapter.ts
  packages/core/src/messaging/queue/notificationMessageQueue.ts
  packages/core/src/messaging/queue/stateCarryingMessageQueue.ts
  packages/in-memory-message-queue-adapter/src/adapter.ts
  packages/in-memory-message-queue-adapter/src/adapter.unit.test.ts
  packages/sqs-message-queue-adapter/package.json
  packages/sqs-message-queue-adapter/src/adapter.ts
  packages/sqs-message-queue-adapter/src/adapter.unit.test.ts
  yarn.lock
Labels: minor
