Repository castore-dev/castore, pull requests merged in 2023-04, with the labels that each got.

#81 feature: add publishMessages to MessageBusAdapter
  README.md
  packages/core/src/messaging/bus/messageBusAdapter.ts
  packages/core/src/messaging/bus/notificationMessageBus.ts
  packages/core/src/messaging/bus/stateCarryingMessageBus.ts
  packages/event-bridge-message-bus-adapter/package.json
  packages/event-bridge-message-bus-adapter/src/adapter.ts
  packages/event-bridge-message-bus-adapter/src/adapter.unit.test.ts
  packages/in-memory-message-bus-adapter/src/adapter.ts
  packages/in-memory-message-bus-adapter/src/adapter.unit.test.ts
  packages/in-memory-message-queue-adapter/src/adapter.unit.test.ts
  yarn.lock
Labels: minor

#82 chore: Add diagrams to readme
  README.md
  assets/docsImg/aggregate.excalidraw
  assets/docsImg/aggregate.png
  assets/docsImg/command.excalidraw
  assets/docsImg/command.png
  assets/docsImg/commandRetry.excalidraw
  assets/docsImg/commandRetry.png
  assets/docsImg/connectedEventStore.excalidraw
  assets/docsImg/connectedEventStore.png
  assets/docsImg/eventStore.excalidraw
  assets/docsImg/eventStore.png
  assets/docsImg/events.excalidraw
  assets/docsImg/events.png
  assets/docsImg/messageBus.excalidraw
  assets/docsImg/messageBus.png
  assets/docsImg/messageQueue.excalidraw
  assets/docsImg/messageQueue.png
Labels: ignore-for-release

#83 feature: test only affected libs
  .github/actions/get-affected-packages-paths/action.yml
  .github/actions/get-affected-packages-paths/get-affected-paths.sh
  .github/actions/install-node-modules/action.yml
  .github/actions/lint-and-tests/action.yml
  .github/actions/package/action.yml
  .github/workflows/test-pr.yml
  nx.json
Labels: minor

#86 fix: bug in message bus and queue types
  packages/core/src/messaging/bus/generics.ts
  packages/core/src/messaging/queue/generics.ts
  packages/core/src/messaging/queue/stateCarryingMessageQueue.fixtures.test.ts
  packages/event-bridge-message-bus-adapter/src/message.ts
  packages/in-memory-message-bus-adapter/src/adapter.ts
  packages/in-memory-message-bus-adapter/src/types.ts
  packages/in-memory-message-queue-adapter/src/adapter.ts
  packages/sqs-message-queue-adapter/src/message.ts
Labels: patch

#89 feature: add visualization in github pages
  .github/workflows/deploy-prototype.yml
  demo/visualization/package.json
  demo/visualization/vite.config.ts
Labels: minor

#90 feature: Redefine event groups api
  demo/blueprint/src/commands/catchPokemon.ts
  packages/core/dependency-cruiser.js
  packages/core/src/command/command.fixtures.test.ts
  packages/core/src/connectedEventStore/connectedEventStore.ts
  packages/core/src/connectedEventStore/connectedEventStore.unit.test.ts
  packages/core/src/event/groupedEvent.ts
  packages/core/src/eventStore/eventStore.fixtures.test.ts
  packages/core/src/eventStore/eventStore.ts
  packages/core/src/eventStore/eventStore.type.test.ts
  packages/core/src/eventStore/eventStore.unit.test.ts
  packages/core/src/eventStore/types.ts
  packages/core/src/index.ts
  packages/core/src/storageAdapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.ts
  packages/inmemory-event-storage-adapter/src/adapter.ts
  packages/json-schema-command/src/command.fixtures.test.ts
  packages/redux-event-storage-adapter/src/adapter.ts
Labels: minor

#94 feature: add eventStore context to storage adapter functions
  packages/core/src/event/groupedEvent.ts
  packages/core/src/eventStore/eventStore.ts
  packages/core/src/eventStore/eventStore.unit.test.ts
  packages/core/src/index.ts
  packages/core/src/storageAdapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
  packages/inmemory-event-storage-adapter/src/adapter.ts
  packages/inmemory-event-storage-adapter/src/adapter.unit.test.ts
  packages/redux-event-storage-adapter/src/adapter.ts
Labels: minor

#98 feature: Re enable inputting timestamp in push event
  README.md
  demo/implementation/functions/catchPokemon/catchPokemon.unit.test.ts
  demo/implementation/package.json
  demo/implementation/tsconfig.json
  demo/implementation/vite.config.js
  demo/visualization/package.json
  packages/core/src/event/eventDetail.ts
  packages/core/src/event/eventDetail.type.test.ts
  packages/core/src/event/eventType.ts
  packages/core/src/event/eventType.type.test.ts
  packages/core/src/event/groupedEvent.ts
  packages/core/src/eventStore/eventStore.type.test.ts
  packages/core/src/eventStore/types.ts
  packages/core/src/index.ts
  packages/core/src/storageAdapter.ts
  packages/dynamodb-event-storage-adapter/package.json
  packages/dynamodb-event-storage-adapter/src/adapter.ts
  packages/dynamodb-event-storage-adapter/src/adapter.unit.test.ts
  packages/event-bridge-message-bus-adapter/package.json
  packages/inmemory-event-storage-adapter/src/adapter.ts
  packages/inmemory-event-storage-adapter/src/adapter.unit.test.ts
  packages/redux-event-storage-adapter/package.json
  packages/redux-event-storage-adapter/src/adapter.ts
  packages/redux-event-storage-adapter/src/getCastoreReducers.ts
  packages/sqs-message-queue-adapter/package.json
  packages/test-tools/package.json
  packages/test-tools/src/mockEventStore.unit.test.ts
  packages/test-tools/src/muteEventStore.unit.test.ts
  yarn.lock
Labels: minor

#102 chore: fix github actions warning
  .github/actions/install-node-modules/action.yml
  .github/workflows/deploy-prototype.yml
  .github/workflows/release-to-npm.yml
Labels: ignore-for-release

#101 fix: set ts-toolbelt as dependency in core
  packages/core/package.json
Labels: patch

#105 patch: add eventGroup doc img
  README.md
  assets/docsImg/eventGroup.excalidraw
  assets/docsImg/eventGroup.png
Labels: patch
